version: '3.7'

services:
  mongo-doctor-case-label:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
    restart: always
    ports:
      - $DB_PORT:27017
    volumes:
      - ./_data/mongo-doctor-case-label:/data/db
